### ISSUE TITLE
报错：cant call method "map" of null use

### ISSUE THREAD

**Issue by kevgithub** [lackhurt/grunt-css-import#2]
合并以后的路劲：‘background: url('../public/../../../../../image/main/sprite.png')’  ，  这种路劲怎么着都是错的吧

**Comment by lackhurt** [comment]
不好意思，最近略忙。这个报错的信息能说得详细一点吗，具体是哪里报错了。

**Comment by lackhurt** [comment]
看起webroot是public目录，注意合并的css一定要在一个webfoot下才好。
