### ISSUE TITLE
Disable auto changing the urls

### ISSUE THREAD

**Issue by panzerdp** [lackhurt/grunt-css-import#3]
Hey @lackhurt 
Thanks for the nice plugin.
I noticed that in some cases it would be useful to disable the auto changing the urls. Probably an option can be added for that?
Also when in url is used base64 data, the auto change url should not be applied. This is breaking the base64 data.
Thanks.

**Comment by lackhurt** [comment]
Thx a lot.
The bug that url used base64 data has been fixed.

**Comment by lackhurt** [comment]
"I noticed that in some cases it would be useful to disable the auto changing the urls. Probably an option can be added for that?"
In this case it may be better to use grunt-contrib-concat.

**Comment by panzerdp** [comment]
Thanks @lackhurt for the fix.
The base64 is not breaking anymore.
