### ISSUE TITLE
Cannot read property 'map' of null

### ISSUE THREAD

**Issue by grahamj** [lackhurt/grunt-css-import#8]
This warning is displayed if the source file does not contain an `@import` line.

**Comment by sweco-senari** [comment]
i noticed this too. my solutions so far:

- create an empty dummy css and @import "../dummy.css";
- use another module

**Comment by grahamj** [comment]
@sweco-senari  Ya I chose the latter as this doesn't seem to be maintained.

**Comment by lackhurt** [comment]
Sorry to fix it so late.
